export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const GET_ERRORS = 'GET_ERRORS';

export const LIST_CANDIDATES = 'LIST_CANDIDATES';
export const GET_CANDIDATE = 'GET_CANDIDATE';
export const CREATE_CANDIDATE = 'CREATE_CANDIDATE';
export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
export const UPDATE_CANDIDATE = 'UPDATE_CANDIDATE';