POST http://localhost:8080/api/candidates/create/ HTTP/1.1
content-type: application/json
Authorization: Bearer xxx

{
    "name": "Tester Testerson",
    "email": "user@bestmail.lol",
    "age": 28,
    "linkedin":"linked.in/defuser",
    "techs":["one", "two", "three"]
}

###

GET  http://localhost:8080/api/candidates/list/
Authorization: Bearer xxx
###

GET http://localhost:8080/api/candidates/get/ID HTTP/1.1
Authorization: Bearer xxx

###

POST http://localhost:8080/api/candidates/update/ID HTTP/1.1
content-type: application/json
Authorization: Bearer xxx

{
    "name": "Tester Testerson the Third",
    "email": "tttt@bestmail.lol",
    "age": 24,
    "linkedin":"linked.in/tttt",
    "techs":["one", "two", "three"]
}


###
POST http://localhost:8080/api/candidates/delete/ID HTTP/1.1
Authorization: Bearer xxx